### ISSUE TITLE
Extended Hugo binary can't be specified on Netlify

### ISSUE THREAD

**Issue by digitalcraftsman** [netlify/binrc#18]
Dear @netlify team,

Hugo 0.43 introduced asset pipelines with SCSS / SASS support. This means that such files can be compiled by Hugo as an additional step during the generation of a website.

Since not all users require this feature Hugo 0.43 and above is shipped in two versions: there's a "normal" version and once called ["extended"](https://gohugo.io/news/0.43-relnotes/#notes) that contains the code for parsing and compiling SCSS / SASS files.

I'm mainly responsible for the maintenance of the Hugo theme site. Recent submissions already make use of the asset pipelines for their theme demos. But Netlify doesn't seem to make use of the extended version of Hugo. You can find the corresponding issue [here](https://github.com/gohugoio/hugoThemes/issues/396).

For me and all other (Hugo) users of Netlify it would be great if the extended version of Hugo is the default binary. Alternatively you could add an option that allows us to switch between the normal and extended Hugo binary.

Please let us know how you approach this problem.

**Comment by ghost** [comment]
Related: https://github.com/netlify/build-image/issues/183

**Comment by digitalcraftsman** [comment]
I'm closing this as a duplicate of #16.
