### ISSUE TITLE
Do a new release?

### ISSUE THREAD

**Issue by Keats** [netlify/binrc#21]
It would be useful for Zola users to have a new release so we can update https://github.com/netlify/build-image to use the latest binrc code?

Thanks

**Comment by polyzen** [comment]
@calavera @bcomnes, any chance we could push this through for another build-image release? Us Zola users have been patiently waiting for some time. :)

**Comment by bcomnes** [comment]
We are doing that today! 🙌

**Comment by bcomnes** [comment]
Ok, this is live
https://twitter.com/Netlify/status/1106281135708033024

**Comment by polyzen** [comment]
@bcomnes, I meant also including a release of the latest PR (#19) that was merged in binrc :p.

**Comment by bcomnes** [comment]
@polyzen Ahh ok, thank you for clarifying.  I'll reopen this and get it into the queue since we are now unblocked on using the latest version of this.

**Comment by chriskrycho** [comment]
Is this resolved by v0.2.9? It looks like it *should* be?

**Comment by bcomnes** [comment]
Maybe? This totally fell off the radar.  Getting back into the sprint queue.

**Comment by Keats** [comment]
The binrc side should be fine, I made a PR to update the build-image: https://github.com/netlify/build-image/pull/308

**Comment by bcomnes** [comment]
@Keats thats released now.  Closing.  Please make some noise if anything is off.

**Comment by Keats** [comment]
I tried it a few minutes ago and it's working fine, thanks a lot!
